---
- hosts: production 
  tasks:
    - name: Install Git
      apt: pkg=git state=installed update_cache=true
      sudo: yes

    - name: Install pip
      apt: pkg=python-pip state=installed update_cache=true
      sudo: yes
    
    - name: install docker-py
      command: pip install docker-py
      sudo: yes

    - stat: path=~/App
      register: repo_exist
    
    - name: Git clone
      command: git clone https://github.com/CSC-DevOps/App.git
      when: repo_exist.stat.exists == False

    - name: Git pull
      command: git pull
      when: repo_exist.stat.exists == True
      args:
        chdir: ~/App
    
    - name: Build Dockerfile
      docker_image: path="/home/ubuntu/App" name="ncsu-app" state=build
      sudo: yes
    
    - name: Tag
      command: docker tag ncsu-app localhost:5000/ncsu:latest
      sudo: yes
   
    - name: push
      command: docker push localhost:5000/ncsu:latest
      sudo: yes
      
    - name: run
      command: docker run -p 50100:8080 -d --name app localhost:5000/ncsu:latest
      sudo: yes 
